config/routes.rb
Rails.application.routes.draw do
  resources :quotes do
        member do
                    post 'like'
        end
  end


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "pages#home"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/quote.rb
class Quote < ApplicationRecord
 # has_rich_text :notes

  validates :saying, presence: true
  validates :said_by, presence: true
  validates :year, presence: true, numericality: {only_integer: true, greater_than: 1800, less_than: 2023}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: %i[ show edit update destroy ]

  # GET /quotes or /quotes.json
  def index
    @quotes = Quote.all
  end

  # GET /quotes/1 or /quotes/1.json
  def show
    @quote = Quote.find(params[:id])
  end

  #counting how many votes from user
  def vote 
    @quote = Quote.find(params[:id])
    @quote.increment!(:vote)

    respond_to do |format|
      format.html {redirect_to @quote}
      format.js 
    end 
  end 
  # GET /quotes/new
  def new
    @quote = Quote.new
  end

  # GET /quotes/1/edit
  def edit
  end

  #number of likes displayed
  def like
    @quote = Quote.find(params[:id])
  end

  # POST /quotes or /quotes.json
  def create
    @quote = Quote.new(quote_params)

    respond_to do |format|
      if @quote.save
        format.html { redirect_to quote_url(@quote), notice: "Quote was successfully created." }
        format.json { render :show, status: :created, location: @quote }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotes/1 or /quotes/1.json
  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to quote_url(@quote), notice: "Quote was successfully updated." }
        format.json { render :show, status: :ok, location: @quote }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1 or /quotes/1.json
  def destroy
    @quote.destroy!

    respond_to do |format|
      format.html { redirect_to quotes_url, notice: "Quote was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def quote_params
      params.require(:quote).permit(:saying, :said_by, :year, :notes)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
   <head>
    <title>Quotes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    
  </head>

  <body>
      <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Welcome to Quotes Page</h1>
<p>Click Below to go to Quotes</p>
<%= link_to 'Click Here for Quotes', quotes_path %>  

app/views/quotes/_form.html.erb
<%= form_with(model: quote) do |form| %>
  <% if quote.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(quote.errors.count, "error") %> prohibited this quote from being saved:</h2>

      <ul>
        <% quote.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :saying, class: "form-label" %>
    <%= form.text_field :saying, class:"form-control" %>
  </div>

  <div>
    <%= form.label :said_by, class: "form-label"%>
    <%= form.text_field :said_by, class:"form-control" %>
  </div>

  <div>
    <%= form.label :year, class: "form-label"%>
    <%= form.text_field :year, class:"form-control" %>
  </div>

  <div>
    <%= form.label :notes, class: "form-label"%>
    <%= form.text_field :notes, class:"form-control" %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/quotes/_quote.html.erb
<div id="<%= dom_id quote %>">



<div class="card">
  <div class="card-header">
    Quote
  </div>

  <div class="card-body">
    <h5 class="card-title"><strong><%=quote.saying%></strong></h5>
    <p class="card-text"><%= "- " + quote.said_by %></p>

    <div class="d-flex gap-2">
    <button type="button" class="btn btn-primary"><i class="bi bi-trash3" style="color: white"><%= link_to "Edit", edit_quote_path(quote), style: "color: white;" %></i></button>

    <button type="button" class="btn btn-success" ><%= link_to "like", like_quote_path(quote), method: :post  %><i class="bi bi-hand-thumbs-up" style="color: white"></i></button>

        <%= button_to @quote, method: :delete, class: "btn btn-danger" do %>
        <i class="bi bi-trash3" style="color: white;"></i> Delete
          <% end %>
</div>
  </div>
</div>

</div>

app/views/quotes/edit.html.erb
<h1>Editing quote</h1>

<%= render "form", quote: @quote %>

<br>

<div class="container">
  <%= link_to "Show this quote", @quote %> |
  <%= link_to "Back to quotes", quotes_path %>
</div>

app/views/quotes/index.html.erb
<p style="color: green"><%= notice %></p>

<header class="flex">
  <h1>Quotes</h1>
  <ul>
    <%= link_to quotes_path(sort_by: "saying") do %>
    <li><button type="button" class="btn btn-primary">Sort by Saying<i class="bi bi-arrow-down-up"></i></button></li>
    <% end %>

    <%= link_to quotes_path(sort_by: "said_by") do %> 
    <li> <button type="button" class="btn btn-primary">Sort By Said By<i class="bi bi-arrow-down-up"></i></button></li>
    <% end %>

    <%= link_to quotes_path(sort_by: "year") do %>
    <li> <button type="button" class="btn btn-primary">Sort by Year<i class="bi bi-arrow-down-up"></i></button></li>
    <% end %>

    <li><%= link_to new_quote_path, class: "btn btn-primary" do %><i class="bi bi-plus"></i> New Quote<% end %></li>

  </ul>
</header>


<div id="quotes">
  <% @quotes.each do |quote| %>
    <%= render quote %>
    <p>
      <%= link_to "Show this quote", quote %>
    </p>
  <% end %>
</div>

app/views/quotes/new.html.erb
<h1>New quote</h1>

<%= render "form", quote: @quote %>

<br>

<div>
  <%= link_to "Back to quotes", quotes_path %>
</div>

app/views/quotes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @quote %>